import { Injectable } from '@nestjs/common';
import { PipelineContext } from '../pipeline.context';
import { PrismaService } from '../../prisma/prisma.service';
import { PipelineStage, JobStatus } from '@prisma/client';

@Injectable()
export class DeliverStage {
  constructor(private readonly prisma: PrismaService) {}

  async execute(context: PipelineContext): Promise<void> {
    console.log(`[Job ${context.jobId}] Assembling final report...`);

    const DISCLAIMER = "This report is generated by an automated AI system for preliminary novelty pre-checking. It does not constitute legal advice or a formal prior art search. Please consult a qualified patent attorney before making IP decisions.";
    
    // Assemble claimsAnalysis array
    const claimsAnalysis = [];
    if (context.scoredClaims && context.extractedClaims && context.candidates) {
      for (const sc of context.scoredClaims) {
        const claimData = context.extractedClaims.find(c => c.claimId === sc.claimId);
        
        const mappedMatches = sc.matches.map(m => {
          const cand = context.candidates!.find(c => c.candidateId === m.candidateId);
          return {
            tier: m.tier,
            similarityScore: m.cosineSimilarity,
            title: cand?.title || 'Unknown Title',
            source: cand?.source || 'unknown',
            url: cand?.url || '',
            explanation: m.explanation || ''
          };
        });

        claimsAnalysis.push({
          claimId: sc.claimId,
          claimText: claimData?.text || 'Unknown Claim',
          matches: mappedMatches
        });
      }
    }

    const allSources = ['arxiv', 'semantic_scholar'];
    const skippedSources = Array.from((context as any).sourcesSkipped || []);
    const sourcesSearched = allSources.filter(s => !skippedSources.includes(s));

    const finalReport = {
      disclaimer: DISCLAIMER,
      documentSummary: context.documentSummary || 'No summary generated.',
      truncationWarning: (context as any).inputTruncated === true,
      claimsAnalysis: claimsAnalysis,
      sourcesSearched: sourcesSearched,
      sourcesSkipped: skippedSources,
      generatedAt: new Date().toISOString()
    };

    // Save to DB and mark as completed
    await this.prisma.job.update({
      where: { id: context.jobId },
      data: {
        stage: PipelineStage.DELIVER,
        status: JobStatus.COMPLETED,
        progressMessage: 'Job complete. Report is ready.',
        report: finalReport as any
      }
    });

    console.log(`[Job ${context.jobId}] Report delivered successfully and job marked as COMPLETED.`);
  }
}
